language: go

go:
  - 1.6

sudo: false

install:
  - go get github.com/stretchr/testify/assert
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  - go get github.com/satori/go.uuid
  - go get gopkg.in/mgo.v2/bson

script:
  - cd $TRAVIS_BUILD_DIR

  - go test -coverprofile=logger.coverprofile ./detector
  - go test -coverprofile=logger.coverprofile ./util
  - go test -coverprofile=logger.coverprofile ./xlog
  # - go test -coverprofile=main.coverprofile

  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/gover
  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN